notifications:
  email: false

language: go
go:
  - "1.11.x"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make check-style
  - make test

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: GJsEG5aHjlp0HF69tVXIxLHQNsZ5jDqp5tGXALJfIxL5gM8CnMOQolHutT2Z1qZNnWKeTRlsTgs+BmLRcGE7+/HOl3Nz1WQS8+T2KReD7Jp7ZP0eHVxBFdqBPIH0q4QtpZ4zTVkR9RTtYElPs1JkhSFFTDA5vfwMwLzM/tqmyZjKvoRjd2IAllxVU0m9t8WseLaumCCCe7ZO/DPWk9jMJnHV3hdFzgG9DCavi5R6UH48IzHWL+zKhnd3NJW7SXAzUMsemhlkfqsX7p5ivd9vvsoR25b4JDm5WF0UfVHW6Fa4JSvFQ9Nm1lI8P4gE92ArPIactyPRanMh7ivakA7Fl5JWeP7AkRZBPCcdEpGQ8FpIGM8RMXTBJV5mKAM3zhfzfe/q6ywkRe6AFNN3kFwHUT7Wd1nkQhzkmQA7tM9fewb5vfwMzAEm3ErDKyBFAkiWeHgRLfAzsw4wsCJ/0a2p1wOkuoI8YHJDVLSJrlelTYpIQk0CPZyc313XUgZTC2D0JSk7sP2/pLt+bBaW895OczQ9WJS374DLp5eHI2tAUrjXsJ5nkb8TbcHfelSwA+ceTEwVMeo6L2Jye0T7B3hFJinG3wNtemCMGHwzqnvmWd884ZSmLGJZRAiql4eYdWFsJSVoqDMxtahOS/Tz9i9+4aqkP4Nja5ULnp3PRChdJRQ=
  skip_cleanup: true
  file_glob: true
  file: "dist/com.cpanato.panda-*.tar.gz"
  on:
    repo: cpanato/mattermost-plugin-panda
    tags: true
