version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cpanato/mattermost-plugin-panda
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make check-style

  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cpanato/mattermost-plugin-panda
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make test

  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cpanato/mattermost-plugin-panda
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make dist
      - persist_to_workspace:
          path: dist/

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
  tagged-build:
    jobs:
      - lint
      - test
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
